imports:
    - { resource: tables.yml }
services:
    posey.aps.listener:
        class: posey\aps\event\main_listener
        arguments:
            - @config
            - @controller.helper
            - @template
            - @dbal.conn
            - @user
            - %core.root_path%
            - %core.php_ext%
            - @auth
            - @request
            - %posey.aps.tables.wall%
            - @notification_manager
            - @service_container
        tags:
            - { name: event.listener }

    posey.aps.notification.type.wall:
        class: posey\aps\notification\wall
        scope: prototype 
        scope: prototype # scope MUST be prototype for this to work!
        arguments:
            - @user_loader
            - @dbal.conn
            - @cache.driver
            - @user
            - @auth
            - @config
            - @controller.helper
            - %core.root_path%
            - %core.php_ext%
            - %tables.notification_types%
            - %tables.notifications%
            - %tables.user_notifications%
        tags:
            - { name: notification.type }